services:
  stride-locker:
    build:
      context: .
      args:
        VITE_STRIDE_SHARED_KEY: ${VITE_STRIDE_SHARED_KEY}
    container_name: stride-locker
    ports:
      - "3005:5173"
    volumes:
      - ./data:/app/data
    env_file:
      - .env.local
    restart: unless-stopped
